catalyst_count/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('upload_data.urls', namespace='upload_data')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('query_builder/', include('query_builder.urls', namespace='query_builder')),
    path('api/query_builder/', include('query_builder.api.urls', namespace='query_builder_api'))
]

query_builder/api/urls.py
from django.urls import path
from .views import ListCompanyDataView

app_name = 'query_builder_api'

urlpatterns = [
	path('', ListCompanyDataView.as_view(), name='query_result_api')
]

query_builder/urls.py
from django.urls import path
from .views import QueryBuilderView, ShowQueryResultView

app_name = 'query_builder'

urlpatterns = [
	path('', QueryBuilderView.as_view(), name='query_builder'),
	path('query_result', ShowQueryResultView.as_view(), name='query_result')
]

user/urls.py
from django.urls import path
from .views import UserListView, DeleteUserView, CreateNewUserView


app_name = 'user'


urlpatterns = [
	path('list_user/', UserListView.as_view(), name='list_user'),
	path('<slug:pk>/delete/', DeleteUserView.as_view(), name='delete_user'),
	path('create_user', CreateNewUserView.as_view(), name='create_user'),
]

query_builder/models.py
from django.db import models

# Create your models here.

query_builder/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from upload_data.models import CompanyModel
from rest_framework import status
from .serializers import FilterCompanyDataSerializer
import json

class ListCompanyDataView(APIView):
	def get(self, request):
		bytes_literal = request.body
		print(len(bytes_literal.decode('utf-8')))
		if len(bytes_literal.decode('utf-8')) == 0:
			return Response({
				'error': 'Please provide filters for querying data',
			},
			status=status.HTTP_400_BAD_REQUEST
		)

		filters = json.loads(request.body)
		queryset = CompanyModel.objects.all()

		year_founded = filters.get('year_founded')

		if year_founded:
			queryset = queryset.filter(year_founded=int(year_founded))
			filters.pop('year_founded')

		city, state = filters.get('city'), filters.get('state')

		if city:
			queryset = queryset.filter(locality__icontains=city.lower())
			filters.pop('city')
		if state:
			queryset = queryset.filter(locality__icontains=state.lower())
			filters.pop('state')

		filters = {
			key:value.lower() for key,value in
			filters.items() if key not in ['year_founded', 'city', 'state']
		}
		queryset = queryset.filter(**filters)
		serializer = FilterCompanyDataSerializer(queryset, many=True)
		return Response({
				'total result found': len(queryset),
				'result': serializer.data
			},
			status=status.HTTP_200_OK
		)

query_builder/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView, View
from catalyst_count.redis import redis
from upload_data.models import CompanyModel
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from django.core.exceptions import ValidationError
from django.contrib.auth.mixins import LoginRequiredMixin


class QueryBuilderView(LoginRequiredMixin, TemplateView):
	template_name = 'query_builder.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['industries'] = redis.sort('industry', alpha=True)
		context['year_founded'] = redis.sort('year_founded')
		context['cities'] = redis.sort(name='city', alpha=True)
		context['states'] = redis.sort('state', alpha=True)
		context['countries'] = redis.sort('country', alpha=True)
		return context



class ShowQueryResultView(ListView):
	model = CompanyModel
	template_name = 'show_query_data.html'

	def get_filter_queryset(self, **kwargs):
		have_values = {
			key: value.lower() for key, value in
			self.request.GET.items() if value.strip() != ''
		}

		queryset = CompanyModel.objects.all()

		if len(have_values) == 0:
			return None

		city = self.request.GET.get('city')
		state = self.request.GET.get('state')

		if city:
			queryset = queryset.filter(locality__icontains=city)
			have_values.pop('city')
		if state:
			queryset = queryset.filter(locality__icontains=state)
			have_values.pop('state')

		if have_values.get('year_founded'):
			have_values['year_founded'] = int(have_values['year_founded'])

		queryset = queryset.filter(**have_values)
		return queryset

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		queryset = self.get_filter_queryset()
		context['result'] = self.get_filter_queryset()
		return context

query_builder/templates/query_builder.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block title %}
Query Builder
{% endblock title %}
{% block content %}
{% include 'components/navbar.html' %}
<div class="container mt-4">
    <h1>Query Builder</h1>
    <form method="GET" action="{% url 'query_builder:query_result' %}">
    <div class="form-group">
        <p class="text-danger">Not sure about the functionality of keyword thus not implemented.</p>
        <label for="textInput">Keyword</label>
        <input type="text" class="form-control" id="textInput" name="keyword">
    </div>
    <p class="text-success">City, state, year founded, industry and country filters are working.</p>
    <div class="form-group">
        <label for="dropdown1">City</label>
        <input type="text" class="form-control" id="textInput1" name="city">
    </div>
    <div class="form-group">
        <label for="dropdown2">State</label>
        <input type="text" class="form-control" id="textInput2" name="state">
    </div>
    <div class="form-group">
        <label for="dropdown3">Year Founded</label>
        <select class="form-control" id="dropdown3" name="year_founded"><option value=""></option>
            {% for year in year_founded %}
            <option value="{{ year|num_to_string }}">{{ year|num_to_string }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="dropdown4">Industry</label>
        <select class="form-control" id="dropdown4" name="industry">
        	<option value=""></option>
            {% for industry in industries %}
            <option value="{{ industry|to_string }}">{{ industry|to_string|title }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="dropdown5">Country</label>
        <select class="form-control" id="dropdown5" name="country">
        	<option value=""></option>
            {% for country in countries %}
            <option value="{{ country|to_string }}">{{ country|to_string|title}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <p class="text-danger">Not sure what functionality Employees(From) and Employees(To) will provide thus not implemented.</p>
        <label for="textInput">Employees(From) </label>
        <input type="number" class="form-control" id="textInput3" name="employee_count_from">
    </div>
    <div class="form-group">
        <label for="textInput">Employees(To)</label>
        <input type="number" class="form-control" id="textInput4" name="employee_count_to">
    </div>
    <!-- Buttons -->
    <button type="submit" class="btn btn-success">Query Data</button>
    <a href="{% url 'query_builder:query_builder' %}" type="button" class="btn btn-danger">Reset</a>
    </form>
</div>
{% endblock content %}

query_builder/templates/show_query_data.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block title %}
Query Builder
{% endblock title %}
{% block content %}
{% include 'components/navbar.html' %}
<div class="container-fluid mt-4">
    <h1>Result</h1>
    {% if result %}
    <h4>Total {{ result| length }} records found</h4>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Domain</th>
                <th scope="col">Year founded</th>
                <th scope="col">Industry</th>
                <th scope="col">Size range</th>
                <th scope="col">Locality</th>
                <th scope="col">Country</th>
                <th scope="col">LinkedIn url</th>
                <th scope="col">Current employee estimate</th>
                <th scope="col">Total employee estimate</th>
            </tr>
        </thead>
        <tbody>
            {% for company in result %}
            <tr>
                <td>{{ company.name|title }}</td>
                <td>{{ company.domain }}</td>
                <td>{{ company.year_founded }}</td>
                <td>{{ company.industry|title }}</td>
                <td>{{ company.size_range }}</td>
                <td>{{ company.locality|title }}</td>
                <td>{{ company.country|title }}</td>
                <td>{{ company.linkedin_url }}</td>
                <td>{{ company.current_employee_estimate }}</td>
                <td>{{ company.total_employee_estimate }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
     {% else %}
    <h4>Please select a filter!</h4>
    {% endif %}
</div>
{% endblock content %}