catalyst_count/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('upload_data.urls', namespace='upload_data')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('query_builder/', include('query_builder.urls', namespace='query_builder')),
    path('api/query_builder/', include('query_builder.api.urls', namespace='query_builder_api'))
]

user/urls.py
from django.urls import path
from .views import UserListView, DeleteUserView, CreateNewUserView


app_name = 'user'


urlpatterns = [
	path('list_user/', UserListView.as_view(), name='list_user'),
	path('<slug:pk>/delete/', DeleteUserView.as_view(), name='delete_user'),
	path('create_user', CreateNewUserView.as_view(), name='create_user'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .model_manager import CustomUserModelManager
import uuid

class CustomUser(AbstractBaseUser, PermissionsMixin):
	uuid = models.UUIDField(default=uuid.uuid4, primary_key=True)
	username = models.CharField(max_length=20, unique=True)
	first_name = models.CharField(max_length=20)
	last_name = models.CharField(max_length=20, blank=True, null=True)
	email = models.EmailField(unique=True, blank=True, null=True)
	is_staff = models.BooleanField(default=False)
	is_active = models.BooleanField(default=False)
	is_superuser = models.BooleanField(default=False)

	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = []

	objects = CustomUserModelManager()

	def __str__(self):
		return f'Name: {self.first_name.title()} {self.last_name.title() if self.last_name else ""} Email: {self.email}'

	def get_full_name(self):
		return self.first_name.title() + ' ' +self.last_name.title() if self.last_name else ''

user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django import forms
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):
	class Meta:
		model = CustomUser
		fields = ('username', 'first_name', 'last_name', 'email')


class CustomUserChangeForm(UserChangeForm):
	class Meta:
		model = CustomUser
		fields = ('username', 'first_name', 'last_name', 'email')


class CreateNewUserForm(forms.ModelForm):
	password = forms.CharField(max_length=30)
	confirm_password = forms.CharField(max_length=30)

	class Meta:
		model = CustomUser
		fields = ('username', 'first_name', 'last_name', 'email')

	def clean(self):
		cleaned_data = super(CreateNewUserForm, self).clean()
		if cleaned_data.get('username').strip() in [None, '']:
			raise ValidationError('Please provide a username')
		if cleaned_data.get('password') != cleaned_data.get('confirm_password'):
			raise ValidationError('Password dont match')
		return cleaned_data

	def save(self, commit=True):
		new_user = super(CreateNewUserForm, self).save(commit=False)
		cleaned_data = self.cleaned_data
		new_user.set_password(cleaned_data.get('password'))
		if commit:
			new_user.save()
		return new_user
		#new_user.set_password()

user/views.py
from django.shortcuts import render
from .models import CustomUser
from .forms import CreateNewUserForm
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, CreateView, ModelFormMixin
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class UserListView(LoginRequiredMixin, ListView):
	model = CustomUser
	paginate_by = 20
	template_name = 'list_user.html'
	context_object_name = 'user_list'

	def get_queryset(self, *args, **kwargs):
		queryset = super(UserListView, self).get_queryset(*args, **kwargs)
		queryset = queryset.values('uuid', 'first_name', 'last_name', 'email', 'is_active')
		return queryset



class DeleteUserView(LoginRequiredMixin, DeleteView):
	model = CustomUser
	template_name = 'delete_user.html'
	success_url = reverse_lazy('user:list_user')



class CreateNewUserView(LoginRequiredMixin, CreateView, ModelFormMixin):
	template_name = 'signup_user.html'
	form_class = CreateNewUserForm
	success_url = reverse_lazy('user:list_user')

	def form_valid(self, form):
		return super().form_valid(form)

user/templates/delete_user.html
{% extends 'base.html' %}
{% block title %} Delete User {% endblock title %}
{% block content %}
<div class="container mt-5">
<form method="post">
    {% csrf_token %}
<p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit" class='btn btn-lg btn-danger'>Delete</button>
</form>
</div>
{% endblock content %}

user/templates/list_user.html
{% extends 'base.html' %}
{% block title %}
Users
{% endblock title %}
{% block content %}
{% include 'components/navbar.html' %}
<div class="d-flex justify-content-between">
      <div class="m-5">
        <a class="btn btn-success btn btn-lg" href="{% url 'user:create_user' %}">Add User</a>
      </div>
 </div>
<table class="table">
  <tbody>
  	{% for user in user_list%}
    <tr>
      <td>{{ user.first_name|title }} {% if user.last_name %} {{ user.last_name|title }} {% else %} {% endif %}</td>
      <td>{{ user.email }}</td>
      {% if user.is_active %}
      <td>Active</td>
      {% else %}
      <td>Not Active</td>
      {% endif %}
      <td><a class="btn btn-danger btn-sm" href="{% url 'user:delete_user' pk=user.uuid %}">Delete</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

user/templates/signup_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
SignUp
{% endblock title %}
{% block content %}
{% include 'components/navbar.html' %}
<div class="container mt-5">
<form method='POST'>
{% csrf_token %}
{{ form|crispy }}
<button type="submit" class="btn btn-success btn-lg">Submit</button>
</form>
</div>
{% endblock content %}