catalyst_count/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('upload_data.urls', namespace='upload_data')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('query_builder/', include('query_builder.urls', namespace='query_builder')),
    path('api/query_builder/', include('query_builder.api.urls', namespace='query_builder_api'))
]

query_builder/urls.py
from django.urls import path
from .views import QueryBuilderView, ShowQueryResultView

app_name = 'query_builder'

urlpatterns = [
	path('', QueryBuilderView.as_view(), name='query_builder'),
	path('query_result', ShowQueryResultView.as_view(), name='query_result')
]

upload_data/urls.py
from django.urls import path
from .views import UploadDataView

app_name = 'upload_data'


urlpatterns = [
	path('', UploadDataView.as_view(), name='upload_data'),
]

user/urls.py
from django.urls import path
from .views import UserListView, DeleteUserView, CreateNewUserView


app_name = 'user'


urlpatterns = [
	path('list_user/', UserListView.as_view(), name='list_user'),
	path('<slug:pk>/delete/', DeleteUserView.as_view(), name='delete_user'),
	path('create_user', CreateNewUserView.as_view(), name='create_user'),
]

upload_data/models.py
from django.db import models
import uuid

class File(models.Model):
	uuid = models.UUIDField(default=uuid.uuid4)
	file = models.FileField()


class CompanyModel(models.Model):
	uuid = models.UUIDField(default=uuid.uuid4, primary_key=True)
	name = models.CharField(max_length=100)
	domain = models.URLField()
	year_founded = models.PositiveSmallIntegerField(blank=True, null=True)
	industry = models.CharField(max_length=250)
	size_range = models.CharField(max_length=100)
	locality = models.CharField(max_length=100)
	country = models.CharField(max_length=100)
	linkedin_url = models.URLField()
	current_employee_estimate = models.PositiveIntegerField()
	total_employee_estimate = models.PositiveIntegerField()

	def save(self, *args, **kwargs):
		if self.year_founded.strip():
			self.year_founded = int(float(self.year_founded))
		else:
			self.year_founded = None
		super(CompanyModel, self).save(*args, **kwargs)

upload_data/forms.py
from django.forms import ModelForm
from .models import File


class UploadForm(ModelForm):
	class Meta:
		model = File
		fields = ('file',)

upload_data/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View, TemplateView
from django.http import JsonResponse
from .models import File
from .forms import UploadForm
from .tasks import upload_to_db
from django.conf import settings
import os



class UploadDataView(LoginRequiredMixin, View):
	def get(self, request):
		form = UploadForm()
		return render(request, 'upload_data.html', context={'form':form})

	def post(self, request):
		form = UploadForm(request.POST, request.FILES)
		if form.is_valid():
			csv_file = form.save()
			print(os.path.join(settings.MEDIA_ROOT, csv_file.file.name))
			file = form.cleaned_data.get('file')
			task = upload_to_db.delay(os.path.join(settings.MEDIA_ROOT, csv_file.file.name))
			return JsonResponse({'data':'Data uploaded', 'task': task.id})
		else:
			return JsonResponse({'data':'Something went wrong!!'})

upload_data/templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Catalyst Count</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'upload_data:upload_data' %}">Upload Data<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'query_builder:query_builder' %}">Query Builder</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:list_user' %}">Users</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

upload_data/templates/components/pagination.html
<div class="container-fluid">
  {% if is_paginated %}
  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}"
 class="page-link">&laquo; PREV </a></li>
    {% endif %}    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}"
 class="page-link"> NEXT &raquo;</a></li>
    {% endif %}
  </ul>
  </nav></div>
{% endif %}
</div>